package com.github.robfitzgerald.banditsearch.sampler

import com.github.robfitzgerald.banditsearch.sampler.pedrosorei.UCBPedrosoReiSamplerTypeclass

object implicits extends SamplerOps with UCBPedrosoReiSamplerTypeclass